# Review queue — prompt.raven

_Generated 2026-07-27 · client `abcl` · 127 candidate(s), none applied yet_

Every quote below is verbatim from a real call — nothing here is generated. Apply an item with:

```
python run_improve.py <prompt.raven> --client abcl --accept N,M,K
```

| | count |
|---|---|
| Anchor gaps (word missing from an existing intent) | 11 |
| Natural openers (real customer particle for an existing say() line) | 115 |
| Uncovered clusters (no existing intent fits — needs a person) | 1 |
| — high confidence | 104 |
| — low confidence | 22 |

---

## [1] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `ओह, माफ़ कीजिए — लगता है यह number सही नहीं है। आपका समय देने के लिए धन्यवाद, आपका दिन शुभ हो।<EOC/>`
- new: `हां, ओह, माफ़ कीजिए — लगता है यह number सही नहीं है। आपका समय देने के लिए धन्यवाद, आपका दिन शुभ हो।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 1`

---

## [2] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `ओह, समझ गई। क्या <<devanagari_name>> जी अभी बात कर सकते हैं?`
- new: `हां, ओह, समझ गई। क्या <<devanagari_name>> जी अभी बात कर सकते हैं?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 2`

---

## [3] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं — हम उन्हें बाद में contact करेंगे। आपका समय देने के लिए धन्यवाद।<EOC/>`
- new: `हां, कोई बात नहीं — हम उन्हें बाद में contact करेंगे। आपका समय देने के लिए धन्यवाद।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 3`

---

## [4] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मुझे खेद है।<EOC/>`
- new: `हां, मुझे खेद है।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 4`

---

## [5] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `तो क्या हम अभी शुरू करें?`
- new: `हां, तो क्या हम अभी शुरू करें?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 5`

---

## [6] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, अपना ख़याल रखियेगा। Goodbye.<EOC/>`
- new: `हां, कोई बात नहीं, अपना ख़याल रखियेगा। Goodbye.<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 6`

---

## [7] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बढ़िया! आप home screen पर आ गए — नीचे Apply Now button दिखेगा, उस पर click करें, फिर बताएं।`
- new: `हां, बढ़िया! आप home screen पर आ गए — नीचे Apply Now button दिखेगा, उस पर click करें, फिर बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 7`

---

## [8] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, मैं आपको दोबारा SMS भेज रही हूँ — कुछ ही seconds में आ जाएगा, आ जाए तो बताएं।`
- new: `हां, कोई बात नहीं, मैं आपको दोबारा SMS भेज रही हूँ — कुछ ही seconds में आ जाएगा, आ जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 8`

---

## [9] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर रही हूँ जो आपकी पूरी help करेंगे, एक moment रुकें।`
- new: `हां, कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर रही हूँ जो आपकी पूरी help करेंगे, एक moment रुकें।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 9`

---

## [10] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `एक बार अपना internet connection check करके link दोबारा try करें — खुल जाए तो बताएं।`
- new: `हां, एक बार अपना internet connection check करके link दोबारा try करें — खुल जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 10`

---

## [11] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर देती हूँ जो आपकी help करेंगे, एक moment रुकें।`
- new: `हां, कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर देती हूँ जो आपकी help करेंगे, एक moment रुकें।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 11`

---

## [12] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह basic details का page है। सबसे पहले अपना पैन number fill करें और हो जाए तो बताएं।`
- new: `हां, यह basic details का page है। सबसे पहले अपना पैन number fill करें और हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 12`

---

## [13] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब पैन के अनुसार full name enter करें, फिर gender, date of birth और marital status select करें — हो जाए तो बताएं।`
- new: `हां, अब पैन के अनुसार full name enter करें, फिर gender, date of birth और marital status select करें — हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 13`

---

## [14] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब अपना personal email address enter करें और हो जाए तो बताएं।`
- new: `हां, अब अपना personal email address enter करें और हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 14`

---

## [15] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब address fill करें — flat या house number, building, street, locality और pincode — सब हो जाए तो बताएं।`
- new: `हां, अब address fill करें — flat या house number, building, street, locality और pincode — सब हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 15`

---

## [16] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह Professional और Employment details का page है — offer fetch करने के लिए ज़रूरी है। पहले employment type select करें — Salaried या Self-Employed।`
- new: `हां, यह Professional और Employment details का page है — offer fetch करने के लिए ज़रूरी है। पहले employment type select करें — Salaried या Self-Employed।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 16`

---

## [17] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Salaried मतलब जहाँ monthly salary या pension account में आती है — government job भी इसमें आती है। Self-Employed मतलब खुद का business, freelance, या contract work।`
- new: `हां, Salaried मतलब जहाँ monthly salary या pension account में आती है — government job भी इसमें आती है। Self-Employed मतलब खुद का business, freelance, या contract work।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 17`

---

## [18] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Monthly income fill करें — यह आपकी net take-home salary है (tax, bonus, benefits छोड़कर)। हो जाए तो बताएं।`
- new: `हां, Monthly income fill करें — यह आपकी net take-home salary है (tax, bonus, benefits छोड़कर)। हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 18`

---

## [19] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब अपनी organization का नाम enter करें और हो जाए तो बताएं।`
- new: `हां, अब अपनी organization का नाम enter करें और हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 19`

---

## [20] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब अपनी official email ID enter करें और हो जाए तो बताएं।`
- new: `हां, अब अपनी official email ID enter करें और हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 20`

---

## [21] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब organization का address और office pincode (6 digits) fill करें — सब हो जाए तो बताएं।`
- new: `हां, अब organization का address और office pincode (6 digits) fill करें — सब हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 21`

---

## [22] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Net monthly income fill करें — अपनी approximate monthly business earnings। हो जाए तो बताएं।`
- new: `हां, Net monthly income fill करें — अपनी approximate monthly business earnings। हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 22`

---

## [23] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब business या company का registered नाम enter करें और हो जाए तो बताएं।`
- new: `हां, अब business या company का registered नाम enter करें और हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 23`

---

## [24] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब business का address और business pincode (6 digits) fill करें — सब हो जाए तो बताएं।`
- new: `हां, अब business का address और business pincode (6 digits) fill करें — सब हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 24`

---

## [25] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Proceed के बाद Udyam Verification page आएगा — Udyam number और registered mobile number enter करके Submit करें।`
- new: `हां, Proceed के बाद Udyam Verification page आएगा — Udyam number और registered mobile number enter करके Submit करें।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 25`

---

## [26] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह final page है जहाँ आप अपना loan amount और final offer देख सकते हैं। क्या आपको loan amount और final offer दिख रहा है?`
- new: `हां, यह final page है जहाँ आप अपना loan amount और final offer देख सकते हैं। क्या आपको loan amount और final offer दिख रहा है?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 26`

---

## [27] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अच्छा, कोई issue लग रहा है — एक minute... मैं आपको Relationship Manager से connect कर देती हूँ जो help करेंगे।`
- new: `हां, अच्छा, कोई issue लग रहा है — एक minute... मैं आपको Relationship Manager से connect कर देती हूँ जो help करेंगे।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 27`

---

## [28] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मैं समझती हूँ — पर जो amount आपकी profile पर eligible होगा वही screen पर show होगा, और वहीं से आप अपना best option choose कर सकते हैं। चलिए आगे बढ़ते हैं?`
- new: `हां, मैं समझती हूँ — पर जो amount आपकी profile पर eligible होगा वही screen पर show होगा, और वहीं से आप अपना best option choose कर सकते हैं। चलिए आगे बढ़ते हैं?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 28`

---

## [29] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `माफ़ कीजिए, शायद line थोड़ी unclear थी — क्या आप एक बार फिर से बताएंगे?`
- new: `हां, माफ़ कीजिए, शायद line थोड़ी unclear थी — क्या आप एक बार फिर से बताएंगे?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 29`

---

## [30] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Page को एक बार refresh या reload करें — फिर बताएं।`
- new: `हां, Page को एक बार refresh या reload करें — फिर बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 30`

---

## [31] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Pincode को ध्यान से re-enter करें — कोई space नहीं होनी चाहिए। Enter होने के बाद city और state check करें। हो जाए तो बताएं।`
- new: `हां, Pincode को ध्यान से re-enter करें — कोई space नहीं होनी चाहिए। Enter होने के बाद city और state check करें। हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 31`

---

## [32] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `City और state fields को manually clear करें, फिर pincode दोबारा enter करें — internet stable रखें। हो जाए तो बताएं।`
- new: `हां, City और state fields को manually clear करें, फिर pincode दोबारा enter करें — internet stable रखें। हो जाए तो बताएं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 32`

---

## [33] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `इसमें थोड़ी technical problem लग रही है — एक बार अलग browser try करें या ABCL app use करें।`
- new: `हां, इसमें थोड़ी technical problem लग रही है — एक बार अलग browser try करें या ABCL app use करें।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 33`

---

## [34] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `ज़रूर। आप कौन सा दिन और समय prefer करेंगे? हम 10 AM से 7 PM, साथों दिन available रहते हैं।`
- new: `हां, ज़रूर। आप कौन सा दिन और समय prefer करेंगे? हम 10 AM से 7 PM, साथों दिन available रहते हैं।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 34`

---

## [35] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई specific time बता दीजिए।`
- new: `हां, कोई specific time बता दीजिए।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 35`

---

## [36] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बिल्कुल! कृपया जल्दी से complete कर दें। धन्यवाद।<EOC/>`
- new: `हां, बिल्कुल! कृपया जल्दी से complete कर दें। धन्यवाद।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 36`

---

## [37] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बिल्कुल, मैं अभी आपको हमारे specialist से connect कर देती हूँ।`
- new: `हां, बिल्कुल, मैं अभी आपको हमारे specialist से connect कर देती हूँ।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 37`

---

## [38] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मैं प्रिया हूँ, Aditya Birla Capital की तरफ से बोल रही हूँ।`
- new: `हां, मैं प्रिया हूँ, Aditya Birla Capital की तरफ से बोल रही हूँ।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 38`

---

## [39] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बहुत बढ़िया! आपकी application review में है — कोई भी update आपको SMS या email पर मिलेगा। क्या कोई और मदद चाहिए?`
- new: `हां, बहुत बढ़िया! आपकी application review में है — कोई भी update आपको SMS या email पर मिलेगा। क्या कोई और मदद चाहिए?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 39`

---

## [40] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह बताने के लिए धन्यवाद, यह तो अच्छी बात है — उम्मीद है आप हमारी services से ख़ुश हैं। हम पर भरोसा करने के लिए बहुत-बहुत धन्यवाद जी।<EOC/>`
- new: `हां, यह बताने के लिए धन्यवाद, यह तो अच्छी बात है — उम्मीद है आप हमारी services से ख़ुश हैं। हम पर भरोसा करने के लिए बहुत-बहुत धन्यवाद जी।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 40`

---

## [41] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`
- new: `हां, कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 41`

---

## [42] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`
- new: `हां, कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 42`

---

## [43] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह बताने के लिए धन्यवाद — मैं इसे हमारी team तक escalate कर देती हूँ। आपके time के लिए धन्यवाद जी।<EOC/>`
- new: `हां, यह बताने के लिए धन्यवाद — मैं इसे हमारी team तक escalate कर देती हूँ। आपके time के लिए धन्यवाद जी।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 43`

---

## [44] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, एक-एक करके बताती हूँ — बस अभी जो अगला step है वही करें।`
- new: `हां, कोई बात नहीं, एक-एक करके बताती हूँ — बस अभी जो अगला step है वही करें।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 44`

---

## [45] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मुझे सच में बहुत खेद है इस inconvenience के लिए — मैं आपकी frustration समझ सकती हूँ। अभी मैं आपको हमारे senior colleague से connect करती हूँ जो इसे personally resolve करेंगे।`
- new: `हां, मुझे सच में बहुत खेद है इस inconvenience के लिए — मैं आपकी frustration समझ सकती हूँ। अभी मैं आपको हमारे senior colleague से connect करती हूँ जो इसे personally resolve करेंगे।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 45`

---

## [46] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `माफ़ कीजिए, मैं इस call पर सिर्फ Hindi या English में ही help कर सकती हूँ।`
- new: `हां, माफ़ कीजिए, मैं इस call पर सिर्फ Hindi या English में ही help कर सकती हूँ।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 46`

---

## [47] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्षमा कीजिए, मैं इस language में help नहीं कर पाऊँगी। आपके time के लिए धन्यवाद।<EOC/>`
- new: `हां, क्षमा कीजिए, मैं इस language में help नहीं कर पाऊँगी। आपके time के लिए धन्यवाद।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 47`

---

## [48] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्या आप सुन रहे हैं?`
- new: `हां, क्या आप सुन रहे हैं?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 48`

---

## [49] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्या आप सुन रहे हैं?`
- new: `हां, क्या आप सुन रहे हैं?`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 49`

---

## [50] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्या आप किसी शांत जगह से बात कर सकते हैं? आवाज़ clearly नहीं आ रही।`
- new: `हां, क्या आप किसी शांत जगह से बात कर सकते हैं? आवाज़ clearly नहीं आ रही।`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 50`

---

## [51] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `लगता है connection में problem है — हमारी team जल्दी आपसे connect करेगी।<EOC/>`
- new: `हां, लगता है connection में problem है — हमारी team जल्दी आपसे connect करेगी।<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 51`

---

## [52] Add `"हां"` as a lead-in

🟢 high confidence · natural opener (insert) · **579 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `आपके time के लिए धन्यवाद जी। Goodbye.<EOC/>`
- new: `हां, आपके time के लिए धन्यवाद जी। Goodbye.<EOC/>`

Real customer turns:

> हां जी, हां जी.
>
> हां जी sir वह करो.
>
> हां जी बोलिए.

**Accept:** `--accept 52`

---

## [53] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `ओह, माफ़ कीजिए — लगता है यह number सही नहीं है। आपका समय देने के लिए धन्यवाद, आपका दिन शुभ हो।<EOC/>`
- new: `जी, ओह, माफ़ कीजिए — लगता है यह number सही नहीं है। आपका समय देने के लिए धन्यवाद, आपका दिन शुभ हो।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 53`

---

## [54] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `ओह, समझ गई। क्या <<devanagari_name>> जी अभी बात कर सकते हैं?`
- new: `जी, ओह, समझ गई। क्या <<devanagari_name>> जी अभी बात कर सकते हैं?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 54`

---

## [55] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं — हम उन्हें बाद में contact करेंगे। आपका समय देने के लिए धन्यवाद।<EOC/>`
- new: `जी, कोई बात नहीं — हम उन्हें बाद में contact करेंगे। आपका समय देने के लिए धन्यवाद।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 55`

---

## [56] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मुझे खेद है।<EOC/>`
- new: `जी, मुझे खेद है।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 56`

---

## [57] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `तो क्या हम अभी शुरू करें?`
- new: `जी, तो क्या हम अभी शुरू करें?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 57`

---

## [58] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, अपना ख़याल रखियेगा। Goodbye.<EOC/>`
- new: `जी, कोई बात नहीं, अपना ख़याल रखियेगा। Goodbye.<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 58`

---

## [59] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बढ़िया! आप home screen पर आ गए — नीचे Apply Now button दिखेगा, उस पर click करें, फिर बताएं।`
- new: `जी, बढ़िया! आप home screen पर आ गए — नीचे Apply Now button दिखेगा, उस पर click करें, फिर बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 59`

---

## [60] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, मैं आपको दोबारा SMS भेज रही हूँ — कुछ ही seconds में आ जाएगा, आ जाए तो बताएं।`
- new: `जी, कोई बात नहीं, मैं आपको दोबारा SMS भेज रही हूँ — कुछ ही seconds में आ जाएगा, आ जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 60`

---

## [61] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर रही हूँ जो आपकी पूरी help करेंगे, एक moment रुकें।`
- new: `जी, कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर रही हूँ जो आपकी पूरी help करेंगे, एक moment रुकें।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 61`

---

## [62] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `एक बार अपना internet connection check करके link दोबारा try करें — खुल जाए तो बताएं।`
- new: `जी, एक बार अपना internet connection check करके link दोबारा try करें — खुल जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 62`

---

## [63] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर देती हूँ जो आपकी help करेंगे, एक moment रुकें।`
- new: `जी, कोई बात नहीं — मैं आपको हमारे Relationship Manager से connect कर देती हूँ जो आपकी help करेंगे, एक moment रुकें।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 63`

---

## [64] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह basic details का page है। सबसे पहले अपना पैन number fill करें और हो जाए तो बताएं।`
- new: `जी, यह basic details का page है। सबसे पहले अपना पैन number fill करें और हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 64`

---

## [65] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब पैन के अनुसार full name enter करें, फिर gender, date of birth और marital status select करें — हो जाए तो बताएं।`
- new: `जी, अब पैन के अनुसार full name enter करें, फिर gender, date of birth और marital status select करें — हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 65`

---

## [66] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब अपना personal email address enter करें और हो जाए तो बताएं।`
- new: `जी, अब अपना personal email address enter करें और हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 66`

---

## [67] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब address fill करें — flat या house number, building, street, locality और pincode — सब हो जाए तो बताएं।`
- new: `जी, अब address fill करें — flat या house number, building, street, locality और pincode — सब हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 67`

---

## [68] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह Professional और Employment details का page है — offer fetch करने के लिए ज़रूरी है। पहले employment type select करें — Salaried या Self-Employed।`
- new: `जी, यह Professional और Employment details का page है — offer fetch करने के लिए ज़रूरी है। पहले employment type select करें — Salaried या Self-Employed।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 68`

---

## [69] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Salaried मतलब जहाँ monthly salary या pension account में आती है — government job भी इसमें आती है। Self-Employed मतलब खुद का business, freelance, या contract work।`
- new: `जी, Salaried मतलब जहाँ monthly salary या pension account में आती है — government job भी इसमें आती है। Self-Employed मतलब खुद का business, freelance, या contract work।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 69`

---

## [70] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Monthly income fill करें — यह आपकी net take-home salary है (tax, bonus, benefits छोड़कर)। हो जाए तो बताएं।`
- new: `जी, Monthly income fill करें — यह आपकी net take-home salary है (tax, bonus, benefits छोड़कर)। हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 70`

---

## [71] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब अपनी organization का नाम enter करें और हो जाए तो बताएं।`
- new: `जी, अब अपनी organization का नाम enter करें और हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 71`

---

## [72] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब अपनी official email ID enter करें और हो जाए तो बताएं।`
- new: `जी, अब अपनी official email ID enter करें और हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 72`

---

## [73] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब organization का address और office pincode (6 digits) fill करें — सब हो जाए तो बताएं।`
- new: `जी, अब organization का address और office pincode (6 digits) fill करें — सब हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 73`

---

## [74] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Net monthly income fill करें — अपनी approximate monthly business earnings। हो जाए तो बताएं।`
- new: `जी, Net monthly income fill करें — अपनी approximate monthly business earnings। हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 74`

---

## [75] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब business या company का registered नाम enter करें और हो जाए तो बताएं।`
- new: `जी, अब business या company का registered नाम enter करें और हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 75`

---

## [76] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अब business का address और business pincode (6 digits) fill करें — सब हो जाए तो बताएं।`
- new: `जी, अब business का address और business pincode (6 digits) fill करें — सब हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 76`

---

## [77] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Proceed के बाद Udyam Verification page आएगा — Udyam number और registered mobile number enter करके Submit करें।`
- new: `जी, Proceed के बाद Udyam Verification page आएगा — Udyam number और registered mobile number enter करके Submit करें।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 77`

---

## [78] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह final page है जहाँ आप अपना loan amount और final offer देख सकते हैं। क्या आपको loan amount और final offer दिख रहा है?`
- new: `जी, यह final page है जहाँ आप अपना loan amount और final offer देख सकते हैं। क्या आपको loan amount और final offer दिख रहा है?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 78`

---

## [79] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `अच्छा, कोई issue लग रहा है — एक minute... मैं आपको Relationship Manager से connect कर देती हूँ जो help करेंगे।`
- new: `जी, अच्छा, कोई issue लग रहा है — एक minute... मैं आपको Relationship Manager से connect कर देती हूँ जो help करेंगे।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 79`

---

## [80] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मैं समझती हूँ — पर जो amount आपकी profile पर eligible होगा वही screen पर show होगा, और वहीं से आप अपना best option choose कर सकते हैं। चलिए आगे बढ़ते हैं?`
- new: `जी, मैं समझती हूँ — पर जो amount आपकी profile पर eligible होगा वही screen पर show होगा, और वहीं से आप अपना best option choose कर सकते हैं। चलिए आगे बढ़ते हैं?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 80`

---

## [81] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `माफ़ कीजिए, शायद line थोड़ी unclear थी — क्या आप एक बार फिर से बताएंगे?`
- new: `जी, माफ़ कीजिए, शायद line थोड़ी unclear थी — क्या आप एक बार फिर से बताएंगे?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 81`

---

## [82] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Page को एक बार refresh या reload करें — फिर बताएं।`
- new: `जी, Page को एक बार refresh या reload करें — फिर बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 82`

---

## [83] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `Pincode को ध्यान से re-enter करें — कोई space नहीं होनी चाहिए। Enter होने के बाद city और state check करें। हो जाए तो बताएं।`
- new: `जी, Pincode को ध्यान से re-enter करें — कोई space नहीं होनी चाहिए। Enter होने के बाद city और state check करें। हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 83`

---

## [84] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `City और state fields को manually clear करें, फिर pincode दोबारा enter करें — internet stable रखें। हो जाए तो बताएं।`
- new: `जी, City और state fields को manually clear करें, फिर pincode दोबारा enter करें — internet stable रखें। हो जाए तो बताएं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 84`

---

## [85] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `इसमें थोड़ी technical problem लग रही है — एक बार अलग browser try करें या ABCL app use करें।`
- new: `जी, इसमें थोड़ी technical problem लग रही है — एक बार अलग browser try करें या ABCL app use करें।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 85`

---

## [86] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `ज़रूर। आप कौन सा दिन और समय prefer करेंगे? हम 10 AM से 7 PM, साथों दिन available रहते हैं।`
- new: `जी, ज़रूर। आप कौन सा दिन और समय prefer करेंगे? हम 10 AM से 7 PM, साथों दिन available रहते हैं।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 86`

---

## [87] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई specific time बता दीजिए।`
- new: `जी, कोई specific time बता दीजिए।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 87`

---

## [88] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बिल्कुल! कृपया जल्दी से complete कर दें। धन्यवाद।<EOC/>`
- new: `जी, बिल्कुल! कृपया जल्दी से complete कर दें। धन्यवाद।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 88`

---

## [89] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बिल्कुल, मैं अभी आपको हमारे specialist से connect कर देती हूँ।`
- new: `जी, बिल्कुल, मैं अभी आपको हमारे specialist से connect कर देती हूँ।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 89`

---

## [90] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मैं प्रिया हूँ, Aditya Birla Capital की तरफ से बोल रही हूँ।`
- new: `जी, मैं प्रिया हूँ, Aditya Birla Capital की तरफ से बोल रही हूँ।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 90`

---

## [91] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `बहुत बढ़िया! आपकी application review में है — कोई भी update आपको SMS या email पर मिलेगा। क्या कोई और मदद चाहिए?`
- new: `जी, बहुत बढ़िया! आपकी application review में है — कोई भी update आपको SMS या email पर मिलेगा। क्या कोई और मदद चाहिए?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 91`

---

## [92] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह बताने के लिए धन्यवाद, यह तो अच्छी बात है — उम्मीद है आप हमारी services से ख़ुश हैं। हम पर भरोसा करने के लिए बहुत-बहुत धन्यवाद जी।<EOC/>`
- new: `जी, यह बताने के लिए धन्यवाद, यह तो अच्छी बात है — उम्मीद है आप हमारी services से ख़ुश हैं। हम पर भरोसा करने के लिए बहुत-बहुत धन्यवाद जी।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 92`

---

## [93] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`
- new: `जी, कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 93`

---

## [94] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`
- new: `जी, कोई बात नहीं, आपका समय देने के लिए धन्यवाद — आपका दिन शुभ हो।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 94`

---

## [95] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `यह बताने के लिए धन्यवाद — मैं इसे हमारी team तक escalate कर देती हूँ। आपके time के लिए धन्यवाद जी।<EOC/>`
- new: `जी, यह बताने के लिए धन्यवाद — मैं इसे हमारी team तक escalate कर देती हूँ। आपके time के लिए धन्यवाद जी।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 95`

---

## [96] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `कोई बात नहीं, एक-एक करके बताती हूँ — बस अभी जो अगला step है वही करें।`
- new: `जी, कोई बात नहीं, एक-एक करके बताती हूँ — बस अभी जो अगला step है वही करें।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 96`

---

## [97] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `मुझे सच में बहुत खेद है इस inconvenience के लिए — मैं आपकी frustration समझ सकती हूँ। अभी मैं आपको हमारे senior colleague से connect करती हूँ जो इसे personally resolve करेंगे।`
- new: `जी, मुझे सच में बहुत खेद है इस inconvenience के लिए — मैं आपकी frustration समझ सकती हूँ। अभी मैं आपको हमारे senior colleague से connect करती हूँ जो इसे personally resolve करेंगे।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 97`

---

## [98] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `माफ़ कीजिए, मैं इस call पर सिर्फ Hindi या English में ही help कर सकती हूँ।`
- new: `जी, माफ़ कीजिए, मैं इस call पर सिर्फ Hindi या English में ही help कर सकती हूँ।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 98`

---

## [99] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्षमा कीजिए, मैं इस language में help नहीं कर पाऊँगी। आपके time के लिए धन्यवाद।<EOC/>`
- new: `जी, क्षमा कीजिए, मैं इस language में help नहीं कर पाऊँगी। आपके time के लिए धन्यवाद।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 99`

---

## [100] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्या आप सुन रहे हैं?`
- new: `जी, क्या आप सुन रहे हैं?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 100`

---

## [101] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्या आप सुन रहे हैं?`
- new: `जी, क्या आप सुन रहे हैं?`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 101`

---

## [102] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `क्या आप किसी शांत जगह से बात कर सकते हैं? आवाज़ clearly नहीं आ रही।`
- new: `जी, क्या आप किसी शांत जगह से बात कर सकते हैं? आवाज़ clearly नहीं आ रही।`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 102`

---

## [103] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `लगता है connection में problem है — हमारी team जल्दी आपसे connect करेगी।<EOC/>`
- new: `जी, लगता है connection में problem है — हमारी team जल्दी आपसे connect करेगी।<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 103`

---

## [104] Add `"जी"` as a lead-in

🟢 high confidence · natural opener (insert) · **175 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `आपके time के लिए धन्यवाद जी। Goodbye.<EOC/>`
- new: `जी, आपके time के लिए धन्यवाद जी। Goodbye.<EOC/>`

Real customer turns:

> जी बोलिए.
>
> जी हो गया.
>
> जी बराबर.

**Accept:** `--accept 104`

---

## [105] Uncovered cluster — 18 turns, 17 calls

🔵 uncovered cluster · always needs a person — naming the intent and writing its answer can't be automated

Best guess: `has_loan_unspecified` (0.61)  ·  runner-up: `prior_attempt_failed` (0.59)  ·  margin: **0.02**

Sample turns:

> उसमें loan दिखा रहा है madam. Pay करने के लिए.  
> <sub>`0139490a-e09f-4efe-bdb1-c91775067e5f-transcript`</sub>
>
> loan amount मिल सकता है.  
> <sub>`07ea36d9-16fc-4cef-ab7c-939240f1b969-transcript`</sub>
>
> अच्छा. Ok. इसमें मुझे कितना loan amount मिल सकता है?  
> <sub>`0d1b55e2-78de-4b4e-a578-b7d2a576867f-transcript`</sub>
>
> Ma'am loan यह दो लाख तिरपन हज़ार आ रहा है.  
> <sub>`298f09f6-2c9d-4e4d-aa5d-e278b94f505c-transcript`</sub>
>
> एक दस लाख loan  
> <sub>`3263832d-cd6a-4ac1-8961-ecad5136b5c9-transcript`</sub>

**Track (no automatic edit possible):** `--accept 105` or `--reject 105`

---

## [106] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, ज़्यादा समय नहीं लगेगा — बस थोड़ा सा समय चाहिए। क्या हम continue करें?`
- new: `जी जी, ज़्यादा समय नहीं लगेगा — बस थोड़ा सा समय चाहिए। क्या हम continue करें?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 106`

---

## [107] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, आपको आदित्य बिरला कैपिटल की तरफ से एक exciting pre-approved loan offer है <<loan_amount>> का — मैं अभी इसी call पर apply करने में मदद कर सकती हूँ। क्या हम शुरू करें?`
- new: `जी जी, आपको आदित्य बिरला कैपिटल की तरफ से एक exciting pre-approved loan offer है <<loan_amount>> का — मैं अभी इसी call पर apply करने में मदद कर सकती हूँ। क्या हम शुरू करें?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 107`

---

## [108] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, आपको आदित्य बिरला कैपिटल की तरफ से एक exciting pre-approved loan offer available है — मैं अभी इसी call पर apply करने में मदद कर सकती हूँ। क्या हम शुरू करें?`
- new: `जी जी, आपको आदित्य बिरला कैपिटल की तरफ से एक exciting pre-approved loan offer available है — मैं अभी इसी call पर apply करने में मदद कर सकती हूँ। क्या हम शुरू करें?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 108`

---

## [109] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, समझ सकती हूँ। यह <<loan_amount>> का pre-approved offer है — documents अभी नहीं चाहिए and process इसी call पर complete हो जाती है। क्या हम एक बार try करें?`
- new: `जी जी, समझ सकती हूँ। यह <<loan_amount>> का pre-approved offer है — documents अभी नहीं चाहिए and process इसी call पर complete हो जाती है। क्या हम एक बार try करें?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 109`

---

## [110] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, समझ सकती हूँ कि अभी interested नहीं हैं। बस बताना चाहूँगी — यह loan अक्सर daily ज़रूरतों या urgent expenses में काम आ जाता है। चाहें तो मैं अभी application करवा दूँ। क्या हम proceed करें?`
- new: `जी जी, समझ सकती हूँ कि अभी interested नहीं हैं। बस बताना चाहूँगी — यह loan अक्सर daily ज़रूरतों या urgent expenses में काम आ जाता है। चाहें तो मैं अभी application करवा दूँ। क्या हम proceed करें?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 110`

---

## [111] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, एक second... अब मैं आपको Relationship Manager से connect कर देती हूँ जो आपका KYC process संभालेंगे — कृपया एक moment रुकें।`
- new: `जी जी, एक second... अब मैं आपको Relationship Manager से connect कर देती हूँ जो आपका KYC process संभालेंगे — कृपया एक moment रुकें।`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 111`

---

## [112] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, अभी profile complete करने पर आपकी eligibility के हिसाब से जो offer available होगा वो screen पर दिख जाएगा, और आप उसमें से choose कर सकते हैं। क्या हम आगे बढ़ें?`
- new: `जी जी, अभी profile complete करने पर आपकी eligibility के हिसाब से जो offer available होगा वो screen पर दिख जाएगा, और आप उसमें से choose कर सकते हैं। क्या हम आगे बढ़ें?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 112`

---

## [113] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, मैं ABCL की automated voice assistant हूँ जो आपकी loan application में मदद कर रही हूँ — ज़रूरत हो तो मैं आपको हमारे team member से भी जुड़वा सकती हूँ।`
- new: `जी जी, मैं ABCL की automated voice assistant हूँ जो आपकी loan application में मदद कर रही हूँ — ज़रूरत हो तो मैं आपको हमारे team member से भी जुड़वा सकती हूँ।`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 113`

---

## [114] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी समझ गई कि आपके पास पहले से एक loan है — फिर भी क्या आप एक बार हमारा यह pre-approved offer सुनना चाहेंगे?`
- new: `जी जी समझ गई कि आपके पास पहले से एक loan है — फिर भी क्या आप एक बार हमारा यह pre-approved offer सुनना चाहेंगे?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 114`

---

## [115] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी, समझ सकती हूँ — यह process बहुत simple है और मैं हर step पर आपके साथ हूँ। क्या हम continue करें?`
- new: `जी जी, समझ सकती हूँ — यह process बहुत simple है और मैं हर step पर आपके साथ हूँ। क्या हम continue करें?`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 115`

---

## [116] Double `"जी"` as a lead-in

🟡 low confidence · natural opener (reduplicate) · **9 calls** in real customer speech

> This reworks an existing say() line — always review the fit yourself, the system only knows the word is common, not whether it fits this specific line.

- old: `जी ज़रूर, मैं फिर से आसान तरीके से बताती हूँ।`
- new: `जी जी ज़रूर, मैं फिर से आसान तरीके से बताती हूँ।`

Real customer turns:

> जी जी शाकिब जी से बात कर रही हैं बोलो.
>
> जी जी. तो Ma'am यह तो बहुत ज़्यादा है उन्नीस point two five पर
>
> जी जी आपसे ही बात कर रही हूं आप.

**Accept:** `--accept 116`

---

## [117] Add `"इधर"` to `address_error`'s recognized phrases

🟡 low confidence · anchor gap · **4 calls** · **1.15x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> इधर internet problem है.
>
> अभी यह bag भी नहीं जा रहा है यह. Proceed वाला आ ही नहीं रहा है. इधर ही आकर रुक रहे.
>
> जी नहीं यार इधर से network खोलने नहीं है. Net problem आ रहा इसीलिए.

**Accept:** `--accept 117`

---

## [118] Add `"लगेगा"` to `query_fee`'s recognized phrases

🟡 low confidence · anchor gap · **3 calls** · **1.36x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> और फिर interest क्या लगेगा? लेकिन इसमें तो interest बहुत लग रहा है ना? यह तो उन्नीस सौ पच्चीस होता र
>
> कितना interest लगेगा इसमें कुछ जानकारी आओ आगे?
>
> Charge कितना लगेगा?

**Accept:** `--accept 118`

---

## [119] Add `"month"` to `query_fee`'s recognized phrases

🟡 low confidence · anchor gap · **3 calls** · **1.75x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> Ma'am इसका बताओ अपनी कर रहे हो उसका per month कितना आएगा कितने साल के लिए रहेगा?
>
> Monthly कितना आता?
>
> आठ हज़ार per month?

**Accept:** `--accept 119`

---

## [120] Add `"मालूम"` to `query_fee`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.64x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> उसको interest कितना पड़ रहा है उसका? Interest Correct madam वह बात correct है. लेकिन मैं interest पू
>
> जो quotation आप अगर बता दिए तो मैं इसके साथ apply कर ले सकता था. Direct apply कर लेंगे बोलो तो कैसा 

**Accept:** `--accept 120`

---

## [121] Add `"score"` to `query_fee`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.64x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> दस लाख का loan तो नहीं मिलेगा. ठीक है? आप मेरा CIBIL score देखकर आप मना कर देंगे. मेरे पास पांच करोड
>
> Hello. इसमें interest वगैरह कितना EMI कितनी आएगी? कितने महीने का है? Madam ब्याज ज़्यादा नहीं है? दो

**Accept:** `--accept 121`

---

## [122] Add `"पचास"` to `query_fee`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.64x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> EMI नहीं भरूंगा चलेगा? अभी interest rate कितना है madam? मेरा final offer कितने आता है? कितना कराया 
>
> अच्छा क्या interest है इसका? पचास हज़ार रुपए का.

**Accept:** `--accept 122`

---

## [123] Add `"final"` to `query_fee`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.17x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> EMI नहीं भरूंगा चलेगा? अभी interest rate कितना है madam? मेरा final offer कितने आता है? कितना कराया 
>
> मुझे जानना है कि EMI calculation कैसा होगा इसका? Ok, आप calculate कीजिए one lakh forty का. कितना होग

**Accept:** `--accept 123`

---

## [124] Add `"network"` to `address_error`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.82x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> हां. नहीं आ रहा है sir network का problem है. अभी रात आठ घंटे का बाद देखती हूं तब शायद network का pr
>
> जी नहीं यार इधर से network खोलने नहीं है. Net problem आ रहा इसीलिए.

**Accept:** `--accept 124`

---

## [125] Add `"सही"` to `address_error`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.36x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> Ma'am connection तो सही आ रहा ma'am यह नहीं हो रहा.
>
> इसमें PIN code number डाल रहा हूं तो यह city तो गलत दिखा रहा है सही city नहीं आ रही है madam हाथरा स

**Accept:** `--accept 125`

---

## [126] Add `"welcome"` to `affirm`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.36x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> Hello. हां. No ma'am अभी मैं बाहर हूं. मैं आपको कल बताऊंगा tomorrow. Welcome welcome tomorrow.
>
> हां बोलिए ना madam. Most welcome आपका. आप बोलिए? हां बताइए ना. बताइए. एकदम एकदम कीजिए. हां, हां कीजि

**Accept:** `--accept 126`

---

## [127] Add `"तैयार"` to `affirm`'s recognized phrases

🟡 low confidence · anchor gap · **2 calls** · **1.36x** lift vs. overall corpus

> Common corpus-wide too, not just in this intent's calls — weigh the lift number before accepting.

Real customer turns:

> हां ठीक है बताओ कैसे करना है? हां हां तैयार हूं एकदम.
>
> बोलो. हां हां शुरू ticket का. हां. हमको लोगों के ज़रूरी आए तब बोलता आए तो ले लेगा. हां भेज दियो हमें

**Accept:** `--accept 127`

---
